# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1ff504bc626f5e98ee53eab53a07ae51bd53b7034ed818be3c2cbba25965c26844d330cf4768b1f9c33b310732038e67ec43887ab13665e460ffebdac6a9507

test:
  secret_key_base: f10cee62e5e2fc3250a409611f24d868359ebc2f0dd0a04d89f06e3ff15d73e83e8a0be1f58f68ae16cad22d7ff8916b7967919d9ceb0e6f5d653de674b5367e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
